version: '3.9'
services:
  azure-function:
    image: mcr.microsoft.com/azure-functions/powershell:4.0
    container_name: azfunc 
    restart: unless-stopped
    env_file:
      - '.env.azfunc'
    links:
      - azurite
    volumes:
      - /home/${USER}/azfunc:/home/site/wwwroot
  
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    restart: unless-stopped